
'create a test file for each file format

With New FileCreator
    .CreateFiles
End With

Class FileCreator
    Private baseName
    Private fso

    Sub Class_Initialize
        baseName = "EncodingAnalyzer.sp"
        Set fso = CreateObject("Scripting.FileSystemObject")
    End Sub

    Sub CreateFiles
        CreateFile "01.txt", 13, 10, 0, 0, "Ascii"
        CreateFile "02.txt", &Hff, &Hfe, 0, 0, "UTF16LE"
        CreateFile "03.txt", &Hfe, &Hff, 0, 0, "UTF16BE"
        CreateFile "04.txt", &H2b, &H2f, &H76, 0, "UTF7"
        CreateFile "05.txt", &Hef, &Hbb, &Hbf, 0, "UTF8"
        CreateFile "06.txt", 0, 0, &Hfe, &Hff, "UTF32"
    End Sub

    Sub CreateFile(suffix, byte0, byte1, byte2, byte3, format)
        Const ForWriting = 2
        Const CreateNew = True
        Dim i, stream, fileObj

        'clear read-only attribute
        On Error Resume Next 'continue if the file does not exist
            Set fileObj = fso.GetFile(baseName & suffix)
            fileObj.Attributes = fileObj.Attributes - 1
            Set fileObj = Nothing
        On Error Goto 0

        'create/overwrite the file
        Set stream = fso.OpenTextFile(baseName & suffix, ForWriting, CreateNew)
        For i = 0 To 3
            Execute("stream.Write Chr(byte" & i & ")")
        Next
        stream.WriteBlankLines(2)
        stream.WriteLine "This is an autogenerated test file in " & format & " format."
        stream.Close
        Set stream = Nothing

        'set read-only attribute
        Set fileObj = fso.GetFile(baseName & suffix)
        fileObj.Attributes = fileObj.Attributes + 1
        Set fileObj = Nothing
    End Sub


    Sub Class_Terminate
        Set fso = Nothing
    End Sub
End Class
