Class MathConstants

    'Property: pi
    'Returns: 3.14159265358979
    'Remarks: pi can be generated by the expression <code> 4 * Atn(1)</code>.
    Property Get pi
        pi = 3.14159265358979
    End Property

    'Property: DegRad
    'Returns pi/180
    'Remark: To convert degrees to radians, multiply degrees by DegRad.
    Property Get DegRad
        DegRad = 0.01745329251994
    End Property

    'Property: RaDeg
    'Returns: 180/pi
    'Remark: To convert radians to degrees, multiply radians by RaDeg. Same as RadDeg. Included for backwards compatibility.
    Property Get RaDeg
        RaDeg = 57.2957795130824
    End Property

    'Property: RadDeg
    'Returns: 180/pi
    'Remark: To convert radians to degrees, multiply radians by RadDeg.
    Property Get RadDeg
        RadDeg = 57.2957795130824
    End Property

    'Property e
    'Returns 2.71828182845905
    'Remark: <em> e</em> can be generated by the expression <code> Exp( 1 )</code>.
    Property Get e
        e = 2.71828182845905
    End Property

End Class
